# Generated by Django 4.2.7 on 2025-10-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_user_role'),
        ('accounts', '0002_oauth'),
    ]

    operations = [
    ]
