import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from './providers'
import { MainNav } from '@/components/MainNav';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-payglobe-card text-payglobe-foreground font-sans antialiased">
        <Providers>
          <header className="border-b border-payglobe-border bg-payglobe-card">
            <div className="container flex items-center h-16">
              <MainNav />
            </div>
          </header>
          <main className="container py-6">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
