# Generated by Django 4.2.7 on 2025-10-28 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('is_biller', models.BooleanField(default=False)),
                ('is_subscription_provider', models.BooleanField(default=False)),
                ('is_remittance_agent', models.BooleanField(default=False)),
                ('biller_code', models.CharField(blank=True, max_length=50)),
                ('biller_category', models.CharField(blank=True, max_length=50)),
                ('subscription_terms', models.TextField(blank=True)),
                ('remittance_license', models.CharField(blank=True, max_length=100)),
                ('supported_countries', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer'), ('crypto', 'Cryptocurrency'), ('mtn_momo', 'MTN Mobile Money'), ('telecel', 'Telecel Cash'), ('airtel_tigo', 'AirtelTigo Money'), ('qr', 'QR Payment')], max_length=20)),
                ('details', models.JSONField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.merchant')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.JSONField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('start_date', models.DateField()),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='basic', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscription_end_date', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('max_stores', models.PositiveIntegerField(default=1)),
                ('max_products', models.PositiveIntegerField(default=50)),
                ('analytics_access', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_subscription', to='users.merchant')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.merchant')),
            ],
        ),
    ]
