# Generated by Django 4.2.7 on 2025-10-31 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_payment_ussdtransaction_scheduledpayout_paymentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payments_merchant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_paymentlog_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
