# Generated by Django 4.2.7 on 2025-10-31 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bill_due_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bill_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bill_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='recipient_country',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='remittance_reference',
        ),
    ]
