# Generated by Django 4.2.7 on 2025-11-03 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_alter_product_store'),
        ('payments', '0007_readd_payment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('africastalking', "Africa's Talking"), ('twilio', 'Twilio'), ('nexmo', 'Nexmo'), ('fallback', 'Fallback')], max_length=20)),
                ('is_healthy', models.BooleanField()),
                ('last_checked', models.DateTimeField()),
                ('response_time', models.FloatField()),
                ('success_rate', models.FloatField(help_text='Last 100 attempts')),
            ],
            options={
                'verbose_name_plural': 'Provider Health',
            },
        ),
        migrations.CreateModel(
            name='VerificationTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_attempts', models.IntegerField()),
                ('success_rate', models.FloatField()),
                ('avg_response_time', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bill_due_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bill_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bill_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='recipient_country',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='remittance_reference',
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('provider', models.CharField(choices=[('africastalking', "Africa's Talking"), ('twilio', 'Twilio'), ('nexmo', 'Nexmo'), ('fallback', 'Fallback')], max_length=20)),
                ('success', models.BooleanField()),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_retry', models.BooleanField(default=False)),
                ('from_country', models.CharField(default='US', max_length=3)),
                ('country_code', models.CharField(default='GH', max_length=3)),
                ('region', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider'], name='payments_ve_provide_ba87a7_idx'), models.Index(fields=['success'], name='payments_ve_success_f559e9_idx'), models.Index(fields=['created_at'], name='payments_ve_created_571e90_idx'), models.Index(fields=['phone_number'], name='payments_ve_phone_n_7d6e82_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrossBorderRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_country', models.CharField(max_length=3)),
                ('amount_sent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reference_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_to_regulator', models.BooleanField(default=False)),
                ('report_reference', models.CharField(blank=True, max_length=50)),
                ('source_of_funds_verified', models.BooleanField(default=False)),
                ('recipient_verified', models.BooleanField(default=False)),
                ('exempt_status', models.CharField(blank=True, max_length=20)),
                ('exemption_status', models.CharField(blank=True, choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], max_length=10, null=True)),
                ('exemption_notes', models.TextField(blank=True)),
                ('exemption_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exemptions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_remittances', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'Cross-Border Remittance',
                'verbose_name_plural': 'Cross-Border Remittances',
            },
        ),
    ]
