import json
from django.core.management.base import BaseCommand
from payments.models import Country, Currency


class Command(BaseCommand):
    help = 'Populate the database with country data'

    def handle(self, *args, **options):
        self.stdout.write('Populating countries...')

        # Country data with codes, names, flag emojis, phone codes, and currency codes
        countries_data = [
            {'code': 'AF', 'name': 'Afghanistan', 'flag_emoji': '🇦🇫', 'phone_code': '93', 'currency_code': 'AFN'},
            {'code': 'AL', 'name': 'Albania', 'flag_emoji': '🇦🇱', 'phone_code': '355', 'currency_code': 'ALL'},
            {'code': 'DZ', 'name': 'Algeria', 'flag_emoji': '🇩🇿', 'phone_code': '213', 'currency_code': 'DZD'},
            {'code': 'AD', 'name': 'Andorra', 'flag_emoji': '🇦🇩', 'phone_code': '376', 'currency_code': 'EUR'},
            {'code': 'AO', 'name': 'Angola', 'flag_emoji': '🇦🇴', 'phone_code': '244', 'currency_code': 'AOA'},
            {'code': 'AG', 'name': 'Antigua and Barbuda', 'flag_emoji': '🇦🇬', 'phone_code': '1-268', 'currency_code': 'XCD'},
            {'code': 'AR', 'name': 'Argentina', 'flag_emoji': '🇦🇷', 'phone_code': '54', 'currency_code': 'ARS'},
            {'code': 'AM', 'name': 'Armenia', 'flag_emoji': '🇦🇲', 'phone_code': '374', 'currency_code': 'AMD'},
            {'code': 'AU', 'name': 'Australia', 'flag_emoji': '🇦🇺', 'phone_code': '61', 'currency_code': 'AUD'},
            {'code': 'AT', 'name': 'Austria', 'flag_emoji': '🇦🇹', 'phone_code': '43', 'currency_code': 'EUR'},
            {'code': 'AZ', 'name': 'Azerbaijan', 'flag_emoji': '🇦🇿', 'phone_code': '994', 'currency_code': 'AZN'},
            {'code': 'BS', 'name': 'Bahamas', 'flag_emoji': '🇧🇸', 'phone_code': '1-242', 'currency_code': 'BSD'},
            {'code': 'BH', 'name': 'Bahrain', 'flag_emoji': '🇧🇭', 'phone_code': '973', 'currency_code': 'BHD'},
            {'code': 'BD', 'name': 'Bangladesh', 'flag_emoji': '🇧🇩', 'phone_code': '880', 'currency_code': 'BDT'},
            {'code': 'BB', 'name': 'Barbados', 'flag_emoji': '🇧🇧', 'phone_code': '1-246', 'currency_code': 'BBD'},
            {'code': 'BY', 'name': 'Belarus', 'flag_emoji': '🇧🇾', 'phone_code': '375', 'currency_code': 'BYN'},
            {'code': 'BE', 'name': 'Belgium', 'flag_emoji': '🇧🇪', 'phone_code': '32', 'currency_code': 'EUR'},
            {'code': 'BZ', 'name': 'Belize', 'flag_emoji': '🇧🇿', 'phone_code': '501', 'currency_code': 'BZD'},
            {'code': 'BJ', 'name': 'Benin', 'flag_emoji': '🇧🇯', 'phone_code': '229', 'currency_code': 'XOF'},
            {'code': 'BT', 'name': 'Bhutan', 'flag_emoji': '🇧🇹', 'phone_code': '975', 'currency_code': 'BTN'},
            {'code': 'BO', 'name': 'Bolivia', 'flag_emoji': '🇧🇴', 'phone_code': '591', 'currency_code': 'BOB'},
            {'code': 'BA', 'name': 'Bosnia and Herzegovina', 'flag_emoji': '🇧🇦', 'phone_code': '387', 'currency_code': 'BAM'},
            {'code': 'BW', 'name': 'Botswana', 'flag_emoji': '🇧🇼', 'phone_code': '267', 'currency_code': 'BWP'},
            {'code': 'BR', 'name': 'Brazil', 'flag_emoji': '🇧🇷', 'phone_code': '55', 'currency_code': 'BRL'},
            {'code': 'BN', 'name': 'Brunei', 'flag_emoji': '🇧🇳', 'phone_code': '673', 'currency_code': 'BND'},
            {'code': 'BG', 'name': 'Bulgaria', 'flag_emoji': '🇧🇬', 'phone_code': '359', 'currency_code': 'BGN'},
            {'code': 'BF', 'name': 'Burkina Faso', 'flag_emoji': '🇧🇫', 'phone_code': '226', 'currency_code': 'XOF'},
            {'code': 'BI', 'name': 'Burundi', 'flag_emoji': '🇧🇮', 'phone_code': '257', 'currency_code': 'BIF'},
            {'code': 'CV', 'name': 'Cabo Verde', 'flag_emoji': '🇨🇻', 'phone_code': '238', 'currency_code': 'CVE'},
            {'code': 'KH', 'name': 'Cambodia', 'flag_emoji': '🇰🇭', 'phone_code': '855', 'currency_code': 'KHR'},
            {'code': 'CM', 'name': 'Cameroon', 'flag_emoji': '🇨🇲', 'phone_code': '237', 'currency_code': 'XAF'},
            {'code': 'CA', 'name': 'Canada', 'flag_emoji': '🇨🇦', 'phone_code': '1', 'currency_code': 'CAD'},
            {'code': 'CF', 'name': 'Central African Republic', 'flag_emoji': '🇨🇫', 'phone_code': '236', 'currency_code': 'XAF'},
            {'code': 'TD', 'name': 'Chad', 'flag_emoji': '🇹🇩', 'phone_code': '235', 'currency_code': 'XAF'},
            {'code': 'CL', 'name': 'Chile', 'flag_emoji': '🇨🇱', 'phone_code': '56', 'currency_code': 'CLP'},
            {'code': 'CN', 'name': 'China', 'flag_emoji': '🇨🇳', 'phone_code': '86', 'currency_code': 'CNY'},
            {'code': 'CO', 'name': 'Colombia', 'flag_emoji': '🇨🇴', 'phone_code': '57', 'currency_code': 'COP'},
            {'code': 'KM', 'name': 'Comoros', 'flag_emoji': '🇰🇲', 'phone_code': '269', 'currency_code': 'KMF'},
            {'code': 'CG', 'name': 'Congo', 'flag_emoji': '🇨🇬', 'phone_code': '242', 'currency_code': 'XAF'},
            {'code': 'CD', 'name': 'Congo (Democratic Republic)', 'flag_emoji': '🇨🇩', 'phone_code': '243', 'currency_code': 'CDF'},
            {'code': 'CK', 'name': 'Cook Islands', 'flag_emoji': '🇨🇰', 'phone_code': '682', 'currency_code': 'NZD'},
            {'code': 'CR', 'name': 'Costa Rica', 'flag_emoji': '🇨🇷', 'phone_code': '506', 'currency_code': 'CRC'},
            {'code': 'CI', 'name': 'Côte d\'Ivoire', 'flag_emoji': '🇨🇮', 'phone_code': '225', 'currency_code': 'XOF'},
            {'code': 'HR', 'name': 'Croatia', 'flag_emoji': '🇭🇷', 'phone_code': '385', 'currency_code': 'EUR'},
            {'code': 'CU', 'name': 'Cuba', 'flag_emoji': '🇨🇺', 'phone_code': '53', 'currency_code': 'CUP'},
            {'code': 'CY', 'name': 'Cyprus', 'flag_emoji': '🇨🇾', 'phone_code': '357', 'currency_code': 'EUR'},
            {'code': 'CZ', 'name': 'Czech Republic', 'flag_emoji': '🇨🇿', 'phone_code': '420', 'currency_code': 'CZK'},
            {'code': 'DK', 'name': 'Denmark', 'flag_emoji': '🇩🇰', 'phone_code': '45', 'currency_code': 'DKK'},
            {'code': 'DJ', 'name': 'Djibouti', 'flag_emoji': '🇩🇯', 'phone_code': '253', 'currency_code': 'DJF'},
            {'code': 'DM', 'name': 'Dominica', 'flag_emoji': '🇩🇲', 'phone_code': '1-767', 'currency_code': 'XCD'},
            {'code': 'DO', 'name': 'Dominican Republic', 'flag_emoji': '🇩🇴', 'phone_code': '1-809', 'currency_code': 'DOP'},
            {'code': 'EC', 'name': 'Ecuador', 'flag_emoji': '🇪🇨', 'phone_code': '593', 'currency_code': 'USD'},
            {'code': 'EG', 'name': 'Egypt', 'flag_emoji': '🇪🇬', 'phone_code': '20', 'currency_code': 'EGP'},
            {'code': 'SV', 'name': 'El Salvador', 'flag_emoji': '🇸🇻', 'phone_code': '503', 'currency_code': 'USD'},
            {'code': 'GQ', 'name': 'Equatorial Guinea', 'flag_emoji': '🇬🇶', 'phone_code': '240', 'currency_code': 'XAF'},
            {'code': 'ER', 'name': 'Eritrea', 'flag_emoji': '🇪🇷', 'phone_code': '291', 'currency_code': 'ERN'},
            {'code': 'EE', 'name': 'Estonia', 'flag_emoji': '🇪🇪', 'phone_code': '372', 'currency_code': 'EUR'},
            {'code': 'SZ', 'name': 'Eswatini', 'flag_emoji': '🇸🇿', 'phone_code': '268', 'currency_code': 'SZL'},
            {'code': 'ET', 'name': 'Ethiopia', 'flag_emoji': '🇪🇹', 'phone_code': '251', 'currency_code': 'ETB'},
            {'code': 'FJ', 'name': 'Fiji', 'flag_emoji': '🇫🇯', 'phone_code': '679', 'currency_code': 'FJD'},
            {'code': 'FI', 'name': 'Finland', 'flag_emoji': '🇫🇮', 'phone_code': '358', 'currency_code': 'EUR'},
            {'code': 'FR', 'name': 'France', 'flag_emoji': '🇫🇷', 'phone_code': '33', 'currency_code': 'EUR'},
            {'code': 'GA', 'name': 'Gabon', 'flag_emoji': '🇬🇦', 'phone_code': '241', 'currency_code': 'XAF'},
            {'code': 'GM', 'name': 'Gambia', 'flag_emoji': '🇬🇲', 'phone_code': '220', 'currency_code': 'GMD'},
            {'code': 'GE', 'name': 'Georgia', 'flag_emoji': '🇬🇪', 'phone_code': '995', 'currency_code': 'GEL'},
            {'code': 'DE', 'name': 'Germany', 'flag_emoji': '🇩🇪', 'phone_code': '49', 'currency_code': 'EUR'},
            {'code': 'GH', 'name': 'Ghana', 'flag_emoji': '🇬🇭', 'phone_code': '233', 'currency_code': 'GHS'},
            {'code': 'GR', 'name': 'Greece', 'flag_emoji': '🇬🇷', 'phone_code': '30', 'currency_code': 'EUR'},
            {'code': 'GD', 'name': 'Grenada', 'flag_emoji': '🇬🇩', 'phone_code': '1-473', 'currency_code': 'XCD'},
            {'code': 'GT', 'name': 'Guatemala', 'flag_emoji': '🇬🇹', 'phone_code': '502', 'currency_code': 'GTQ'},
            {'code': 'GN', 'name': 'Guinea', 'flag_emoji': '🇬🇳', 'phone_code': '224', 'currency_code': 'GNF'},
            {'code': 'GW', 'name': 'Guinea-Bissau', 'flag_emoji': '🇬🇼', 'phone_code': '245', 'currency_code': 'XOF'},
            {'code': 'GY', 'name': 'Guyana', 'flag_emoji': '🇬🇾', 'phone_code': '592', 'currency_code': 'GYD'},
            {'code': 'HT', 'name': 'Haiti', 'flag_emoji': '🇭🇹', 'phone_code': '509', 'currency_code': 'HTG'},
            {'code': 'HN', 'name': 'Honduras', 'flag_emoji': '🇭🇳', 'phone_code': '504', 'currency_code': 'HNL'},
            {'code': 'HU', 'name': 'Hungary', 'flag_emoji': '🇭🇺', 'phone_code': '36', 'currency_code': 'HUF'},
            {'code': 'IS', 'name': 'Iceland', 'flag_emoji': '🇮🇸', 'phone_code': '354', 'currency_code': 'ISK'},
            {'code': 'IN', 'name': 'India', 'flag_emoji': '🇮🇳', 'phone_code': '91', 'currency_code': 'INR'},
            {'code': 'ID', 'name': 'Indonesia', 'flag_emoji': '🇮🇩', 'phone_code': '62', 'currency_code': 'IDR'},
            {'code': 'IR', 'name': 'Iran', 'flag_emoji': '🇮🇷', 'phone_code': '98', 'currency_code': 'IRR'},
            {'code': 'IQ', 'name': 'Iraq', 'flag_emoji': '🇮🇶', 'phone_code': '964', 'currency_code': 'IQD'},
            {'code': 'IE', 'name': 'Ireland', 'flag_emoji': '🇮🇪', 'phone_code': '353', 'currency_code': 'EUR'},
            {'code': 'IL', 'name': 'Israel', 'flag_emoji': '🇮🇱', 'phone_code': '972', 'currency_code': 'ILS'},
            {'code': 'IT', 'name': 'Italy', 'flag_emoji': '🇮🇹', 'phone_code': '39', 'currency_code': 'EUR'},
            {'code': 'JM', 'name': 'Jamaica', 'flag_emoji': '🇯🇲', 'phone_code': '1-876', 'currency_code': 'JMD'},
            {'code': 'JP', 'name': 'Japan', 'flag_emoji': '🇯🇵', 'phone_code': '81', 'currency_code': 'JPY'},
            {'code': 'JO', 'name': 'Jordan', 'flag_emoji': '🇯🇴', 'phone_code': '962', 'currency_code': 'JOD'},
            {'code': 'KZ', 'name': 'Kazakhstan', 'flag_emoji': '🇰🇿', 'phone_code': '7', 'currency_code': 'KZT'},
            {'code': 'KE', 'name': 'Kenya', 'flag_emoji': '🇰🇪', 'phone_code': '254', 'currency_code': 'KES'},
            {'code': 'KI', 'name': 'Kiribati', 'flag_emoji': '🇰🇮', 'phone_code': '686', 'currency_code': 'AUD'},
            {'code': 'KP', 'name': 'Korea (North)', 'flag_emoji': '🇰🇵', 'phone_code': '850', 'currency_code': 'KPW'},
            {'code': 'KR', 'name': 'Korea (South)', 'flag_emoji': '🇰🇷', 'phone_code': '82', 'currency_code': 'KRW'},
            {'code': 'KW', 'name': 'Kuwait', 'flag_emoji': '🇰🇼', 'phone_code': '965', 'currency_code': 'KWD'},
            {'code': 'KG', 'name': 'Kyrgyzstan', 'flag_emoji': '🇰🇬', 'phone_code': '996', 'currency_code': 'KGS'},
            {'code': 'LA', 'name': 'Laos', 'flag_emoji': '🇱🇦', 'phone_code': '856', 'currency_code': 'LAK'},
            {'code': 'LV', 'name': 'Latvia', 'flag_emoji': '🇱🇻', 'phone_code': '371', 'currency_code': 'EUR'},
            {'code': 'LB', 'name': 'Lebanon', 'flag_emoji': '🇱🇧', 'phone_code': '961', 'currency_code': 'LBP'},
            {'code': 'LS', 'name': 'Lesotho', 'flag_emoji': '🇱🇸', 'phone_code': '266', 'currency_code': 'LSL'},
            {'code': 'LR', 'name': 'Liberia', 'flag_emoji': '🇱🇷', 'phone_code': '231', 'currency_code': 'LRD'},
            {'code': 'LY', 'name': 'Libya', 'flag_emoji': '🇱🇾', 'phone_code': '218', 'currency_code': 'LYD'},
            {'code': 'LI', 'name': 'Liechtenstein', 'flag_emoji': '🇱🇮', 'phone_code': '423', 'currency_code': 'CHF'},
            {'code': 'LT', 'name': 'Lithuania', 'flag_emoji': '🇱🇹', 'phone_code': '370', 'currency_code': 'EUR'},
            {'code': 'LU', 'name': 'Luxembourg', 'flag_emoji': '🇱🇺', 'phone_code': '352', 'currency_code': 'EUR'},
            {'code': 'MG', 'name': 'Madagascar', 'flag_emoji': '🇲🇬', 'phone_code': '261', 'currency_code': 'MGA'},
            {'code': 'MW', 'name': 'Malawi', 'flag_emoji': '🇲🇼', 'phone_code': '265', 'currency_code': 'MWK'},
            {'code': 'MY', 'name': 'Malaysia', 'flag_emoji': '🇲🇾', 'phone_code': '60', 'currency_code': 'MYR'},
            {'code': 'MV', 'name': 'Maldives', 'flag_emoji': '🇲🇻', 'phone_code': '960', 'currency_code': 'MVR'},
            {'code': 'ML', 'name': 'Mali', 'flag_emoji': '🇲🇱', 'phone_code': '223', 'currency_code': 'XOF'},
            {'code': 'MT', 'name': 'Malta', 'flag_emoji': '🇲🇹', 'phone_code': '356', 'currency_code': 'EUR'},
            {'code': 'MH', 'name': 'Marshall Islands', 'flag_emoji': '🇲🇭', 'phone_code': '692', 'currency_code': 'USD'},
            {'code': 'MR', 'name': 'Mauritania', 'flag_emoji': '🇲🇷', 'phone_code': '222', 'currency_code': 'MRU'},
            {'code': 'MU', 'name': 'Mauritius', 'flag_emoji': '🇲🇺', 'phone_code': '230', 'currency_code': 'MUR'},
            {'code': 'MX', 'name': 'Mexico', 'flag_emoji': '🇲🇽', 'phone_code': '52', 'currency_code': 'MXN'},
            {'code': 'FM', 'name': 'Micronesia', 'flag_emoji': '🇫🇲', 'phone_code': '691', 'currency_code': 'USD'},
            {'code': 'MD', 'name': 'Moldova', 'flag_emoji': '🇲🇩', 'phone_code': '373', 'currency_code': 'MDL'},
            {'code': 'MC', 'name': 'Monaco', 'flag_emoji': '🇲🇨', 'phone_code': '377', 'currency_code': 'EUR'},
            {'code': 'MN', 'name': 'Mongolia', 'flag_emoji': '🇲🇳', 'phone_code': '976', 'currency_code': 'MNT'},
            {'code': 'ME', 'name': 'Montenegro', 'flag_emoji': '🇲🇪', 'phone_code': '382', 'currency_code': 'EUR'},
            {'code': 'MS', 'name': 'Montserrat', 'flag_emoji': '🇲🇸', 'phone_code': '1-664', 'currency_code': 'XCD'},
            {'code': 'MA', 'name': 'Morocco', 'flag_emoji': '🇲🇦', 'phone_code': '212', 'currency_code': 'MAD'},
            {'code': 'MZ', 'name': 'Mozambique', 'flag_emoji': '🇲🇿', 'phone_code': '258', 'currency_code': 'MZN'},
            {'code': 'MM', 'name': 'Myanmar', 'flag_emoji': '🇲🇲', 'phone_code': '95', 'currency_code': 'MMK'},
            {'code': 'NA', 'name': 'Namibia', 'flag_emoji': '🇳🇦', 'phone_code': '264', 'currency_code': 'NAD'},
            {'code': 'NR', 'name': 'Nauru', 'flag_emoji': '🇳🇷', 'phone_code': '674', 'currency_code': 'AUD'},
            {'code': 'NP', 'name': 'Nepal', 'flag_emoji': '🇳🇵', 'phone_code': '977', 'currency_code': 'NPR'},
            {'code': 'NL', 'name': 'Netherlands', 'flag_emoji': '🇳🇱', 'phone_code': '31', 'currency_code': 'EUR'},
            {'code': 'NZ', 'name': 'New Zealand', 'flag_emoji': '🇳🇿', 'phone_code': '64', 'currency_code': 'NZD'},
            {'code': 'NI', 'name': 'Nicaragua', 'flag_emoji': '🇳🇮', 'phone_code': '505', 'currency_code': 'NIO'},
            {'code': 'NE', 'name': 'Niger', 'flag_emoji': '🇳🇪', 'phone_code': '227', 'currency_code': 'XOF'},
            {'code': 'NG', 'name': 'Nigeria', 'flag_emoji': '🇳🇬', 'phone_code': '234', 'currency_code': 'NGN'},
            {'code': 'NU', 'name': 'Niue', 'flag_emoji': '🇳🇺', 'phone_code': '683', 'currency_code': 'NZD'},
            {'code': 'MK', 'name': 'North Macedonia', 'flag_emoji': '🇲🇰', 'phone_code': '389', 'currency_code': 'MKD'},
            {'code': 'NO', 'name': 'Norway', 'flag_emoji': '🇳🇴', 'phone_code': '47', 'currency_code': 'NOK'},
            {'code': 'OM', 'name': 'Oman', 'flag_emoji': '🇴🇲', 'phone_code': '968', 'currency_code': 'OMR'},
            {'code': 'PK', 'name': 'Pakistan', 'flag_emoji': '🇵🇰', 'phone_code': '92', 'currency_code': 'PKR'},
            {'code': 'PW', 'name': 'Palau', 'flag_emoji': '🇵🇼', 'phone_code': '680', 'currency_code': 'USD'},
            {'code': 'PA', 'name': 'Panama', 'flag_emoji': '🇵🇦', 'phone_code': '507', 'currency_code': 'PAB'},
            {'code': 'PG', 'name': 'Papua New Guinea', 'flag_emoji': '🇵🇬', 'phone_code': '675', 'currency_code': 'PGK'},
            {'code': 'PY', 'name': 'Paraguay', 'flag_emoji': '🇵🇾', 'phone_code': '595', 'currency_code': 'PYG'},
            {'code': 'PE', 'name': 'Peru', 'flag_emoji': '🇵🇪', 'phone_code': '51', 'currency_code': 'PEN'},
            {'code': 'PH', 'name': 'Philippines', 'flag_emoji': '🇵🇭', 'phone_code': '63', 'currency_code': 'PHP'},
            {'code': 'PL', 'name': 'Poland', 'flag_emoji': '🇵🇱', 'phone_code': '48', 'currency_code': 'PLN'},
            {'code': 'PT', 'name': 'Portugal', 'flag_emoji': '🇵🇹', 'phone_code': '351', 'currency_code': 'EUR'},
            {'code': 'QA', 'name': 'Qatar', 'flag_emoji': '🇶🇦', 'phone_code': '974', 'currency_code': 'QAR'},
            {'code': 'RO', 'name': 'Romania', 'flag_emoji': '🇷🇴', 'phone_code': '40', 'currency_code': 'RON'},
            {'code': 'RU', 'name': 'Russia', 'flag_emoji': '🇷🇺', 'phone_code': '7', 'currency_code': 'RUB'},
            {'code': 'RW', 'name': 'Rwanda', 'flag_emoji': '🇷🇼', 'phone_code': '250', 'currency_code': 'RWF'},
            {'code': 'WS', 'name': 'Samoa', 'flag_emoji': '🇼🇸', 'phone_code': '685', 'currency_code': 'WST'},
            {'code': 'SM', 'name': 'San Marino', 'flag_emoji': '🇸🇲', 'phone_code': '378', 'currency_code': 'EUR'},
            {'code': 'ST', 'name': 'São Tomé and Príncipe', 'flag_emoji': '🇸🇹', 'phone_code': '239', 'currency_code': 'STN'},
            {'code': 'SA', 'name': 'Saudi Arabia', 'flag_emoji': '🇸🇦', 'phone_code': '966', 'currency_code': 'SAR'},
            {'code': 'SN', 'name': 'Senegal', 'flag_emoji': '🇸🇳', 'phone_code': '221', 'currency_code': 'XOF'},
            {'code': 'RS', 'name': 'Serbia', 'flag_emoji': '🇷🇸', 'phone_code': '381', 'currency_code': 'RSD'},
            {'code': 'SC', 'name': 'Seychelles', 'flag_emoji': '🇸🇨', 'phone_code': '248', 'currency_code': 'SCR'},
            {'code': 'SL', 'name': 'Sierra Leone', 'flag_emoji': '🇸🇱', 'phone_code': '232', 'currency_code': 'SLL'},
            {'code': 'SG', 'name': 'Singapore', 'flag_emoji': '🇸🇬', 'phone_code': '65', 'currency_code': 'SGD'},
            {'code': 'SK', 'name': 'Slovakia', 'flag_emoji': '🇸🇰', 'phone_code': '421', 'currency_code': 'EUR'},
            {'code': 'SI', 'name': 'Slovenia', 'flag_emoji': '🇸🇮', 'phone_code': '386', 'currency_code': 'EUR'},
            {'code': 'SB', 'name': 'Solomon Islands', 'flag_emoji': '🇸🇧', 'phone_code': '677', 'currency_code': 'SBD'},
            {'code': 'SO', 'name': 'Somalia', 'flag_emoji': '🇸🇴', 'phone_code': '252', 'currency_code': 'SOS'},
            {'code': 'ZA', 'name': 'South Africa', 'flag_emoji': '🇿🇦', 'phone_code': '27', 'currency_code': 'ZAR'},
            {'code': 'SS', 'name': 'South Sudan', 'flag_emoji': '🇸🇸', 'phone_code': '211', 'currency_code': 'SSP'},
            {'code': 'ES', 'name': 'Spain', 'flag_emoji': '🇪🇸', 'phone_code': '34', 'currency_code': 'EUR'},
            {'code': 'LK', 'name': 'Sri Lanka', 'flag_emoji': '🇱🇰', 'phone_code': '94', 'currency_code': 'LKR'},
            {'code': 'SD', 'name': 'Sudan', 'flag_emoji': '🇸🇩', 'phone_code': '249', 'currency_code': 'SDG'},
            {'code': 'SR', 'name': 'Suriname', 'flag_emoji': '🇸🇷', 'phone_code': '597', 'currency_code': 'SRD'},
            {'code': 'SE', 'name': 'Sweden', 'flag_emoji': '🇸🇪', 'phone_code': '46', 'currency_code': 'SEK'},
            {'code': 'CH', 'name': 'Switzerland', 'flag_emoji': '🇨🇭', 'phone_code': '41', 'currency_code': 'CHF'},
            {'code': 'SY', 'name': 'Syria', 'flag_emoji': '🇸🇾', 'phone_code': '963', 'currency_code': 'SYP'},
            {'code': 'TW', 'name': 'Taiwan', 'flag_emoji': '🇹🇼', 'phone_code': '886', 'currency_code': 'TWD'},
            {'code': 'TJ', 'name': 'Tajikistan', 'flag_emoji': '🇹🇯', 'phone_code': '992', 'currency_code': 'TJS'},
            {'code': 'TZ', 'name': 'Tanzania', 'flag_emoji': '🇹🇿', 'phone_code': '255', 'currency_code': 'TZS'},
            {'code': 'TH', 'name': 'Thailand', 'flag_emoji': '🇹🇭', 'phone_code': '66', 'currency_code': 'THB'},
            {'code': 'TL', 'name': 'Timor-Leste', 'flag_emoji': '🇹🇱', 'phone_code': '670', 'currency_code': 'USD'},
            {'code': 'TG', 'name': 'Togo', 'flag_emoji': '🇹🇬', 'phone_code': '228', 'currency_code': 'XOF'},
            {'code': 'TO', 'name': 'Tonga', 'flag_emoji': '🇹🇴', 'phone_code': '676', 'currency_code': 'TOP'},
            {'code': 'TT', 'name': 'Trinidad and Tobago', 'flag_emoji': '🇹🇹', 'phone_code': '1-868', 'currency_code': 'TTD'},
            {'code': 'TN', 'name': 'Tunisia', 'flag_emoji': '🇹🇳', 'phone_code': '216', 'currency_code': 'TND'},
            {'code': 'TR', 'name': 'Turkey', 'flag_emoji': '🇹🇷', 'phone_code': '90', 'currency_code': 'TRY'},
            {'code': 'TM', 'name': 'Turkmenistan', 'flag_emoji': '🇹🇲', 'phone_code': '993', 'currency_code': 'TMT'},
            {'code': 'TV', 'name': 'Tuvalu', 'flag_emoji': '🇹🇻', 'phone_code': '688', 'currency_code': 'AUD'},
            {'code': 'UG', 'name': 'Uganda', 'flag_emoji': '🇺🇬', 'phone_code': '256', 'currency_code': 'UGX'},
            {'code': 'UA', 'name': 'Ukraine', 'flag_emoji': '🇺🇦', 'phone_code': '380', 'currency_code': 'UAH'},
            {'code': 'AE', 'name': 'United Arab Emirates', 'flag_emoji': '🇦🇪', 'phone_code': '971', 'currency_code': 'AED'},
            {'code': 'GB', 'name': 'United Kingdom', 'flag_emoji': '🇬🇧', 'phone_code': '44', 'currency_code': 'GBP'},
            {'code': 'US', 'name': 'United States', 'flag_emoji': '🇺🇸', 'phone_code': '1', 'currency_code': 'USD'},
            {'code': 'UY', 'name': 'Uruguay', 'flag_emoji': '🇺🇾', 'phone_code': '598', 'currency_code': 'UYU'},
            {'code': 'UZ', 'name': 'Uzbekistan', 'flag_emoji': '🇺🇿', 'phone_code': '998', 'currency_code': 'UZS'},
            {'code': 'VU', 'name': 'Vanuatu', 'flag_emoji': '🇻🇺', 'phone_code': '678', 'currency_code': 'VUV'},
            {'code': 'VA', 'name': 'Vatican City', 'flag_emoji': '🇻🇦', 'phone_code': '379', 'currency_code': 'EUR'},
            {'code': 'VE', 'name': 'Venezuela', 'flag_emoji': '🇻🇪', 'phone_code': '58', 'currency_code': 'VES'},
            {'code': 'VN', 'name': 'Vietnam', 'flag_emoji': '🇻🇳', 'phone_code': '84', 'currency_code': 'VND'},
            {'code': 'YE', 'name': 'Yemen', 'flag_emoji': '🇾🇪', 'phone_code': '967', 'currency_code': 'YER'},
            {'code': 'ZM', 'name': 'Zambia', 'flag_emoji': '🇿🇲', 'phone_code': '260', 'currency_code': 'ZMW'},
            {'code': 'ZW', 'name': 'Zimbabwe', 'flag_emoji': '🇿🇼', 'phone_code': '263', 'currency_code': 'ZWL'},
        ]

        created_count = 0
        updated_count = 0

        for country_data in countries_data:
            currency = None
            if country_data['currency_code']:
                try:
                    currency = Currency.objects.get(code=country_data['currency_code'])
                except Currency.DoesNotExist:
                    self.stdout.write(
                        self.style.WARNING(
                            f"Currency {country_data['currency_code']} not found for {country_data['name']}"
                        )
                    )

            country, created = Country.objects.update_or_create(
                code=country_data['code'],
                defaults={
                    'name': country_data['name'],
                    'flag_emoji': country_data['flag_emoji'],
                    'phone_code': country_data['phone_code'],
                    'currency': currency,
                    'is_active': True
                }
            )

            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully populated countries: {created_count} created, {updated_count} updated'
            )
        )
